name: TemanTuli
options:
  minimumXcodeGenVersion: 2.38.0
packages: {}
targets:
  TemanTuli:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TemanTuliApp/Sources
    info:
      path: TemanTuliApp/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: Teman Tuli
        NSMicrophoneUsageDescription: Teman Tuli membutuhkan mikrofon untuk membuat live caption saat kelas.
        NSSpeechRecognitionUsageDescription: Teman Tuli menggunakan speech recognition untuk mengubah suara menjadi teks caption.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sulhan.temantuli
        SWIFT_VERSION: 5.9
    scheme:
      testTargets:
        - TemanTuliTests
        - TemanTuliUITests
  TemanTuliTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TemanTuliApp/Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TemanTuli
  TemanTuliUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TemanTuliApp/UITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: TemanTuli
    dependencies:
      - target: TemanTuli
